### ISSUE TITLE
可否增加一下爬虫的暂停时间

### ISSUE THREAD

**Issue by barnett2010** [Python3Spiders/WeiboSuperSpider#12]
我发现微博限制的比较厉害，评论较多时，很容易提示服务器走丢
如果限制脚本运行几秒 随机停几秒 会不会好一点
WeiboSuperCommentScrapy.py

**Comment by barnett2010** [comment]
单条微博的源码显示 mid  id的方式又变了。
变成name=数字 了

**Comment by urawall** [comment]
> 
> 
> 我发现微博限制的比较厉害，评论较多时，很容易提示服务器走丢
> 如果限制脚本运行几秒 随机停几秒 会不会好一点
> WeiboSuperCommentScrapy.py

TAT每次评论爬到1K左右就被切断了……小白试了试time.sleep()数值改大一些，还是不行，到1K就断了。不晓得什么原因
