### ISSUE TITLE
登陆时输入验证码，报错。

### ISSUE THREAD

**Issue by wutongsuimeng** [Python3Spiders/WeiboSuperSpider#13]
res = requests.get(url=next_url.format(id, id, max_id,id_type), headers=headers,cookies=cookie_dict)
UnboundLocalError: local variable 'max_id' referenced before assignment

**Comment by inspurer** [comment]
账号开了双重验证吧

**Comment by wutongsuimeng** [comment]
> 
> 
> 账号开了双重验证吧

没有开双重验证。

**Comment by inspurer** [comment]
是否是 ticket 错误？

**Comment by wutongsuimeng** [comment]
> 
> 
> 是否是 ticket 错误？

也不是。我想可能是因为我爬的那个文章是粉丝可见的吧。因为我试了一下爬别的文章，就顺利爬到评论了。

**Comment by inspurer** [comment]
嗯嗯那就是这个原因了
