### ISSUE TITLE
关于WeiboSuperCommentScrapy.py的评论点赞数问题

### ISSUE THREAD

**Issue by heyauri** [Python3Spiders/WeiboSuperSpider#17]
我用浏览器看https://m.weibo.cn/comments/hotflow?.. 这个请求的时候看到返回的data里面每条comment都是有"like_count"这个表示点赞数的字段的，但在使用WeiboSuperCommentScrapy.py的时候没有获取到相应的字段。有点疑惑，看了好久也没找到什么原因，不知道作者大大有什么想法？
谢谢~

**Comment by inspurer** [comment]
其实是都有的，只不过我原来在 SuperComment 爬虫里没有做解析和保存，现在新加了，欢迎尝试~
