### ISSUE TITLE
按照方法放了cookie运行后出现这样的错误

### ISSUE THREAD

**Issue by EdelweissGriffin** [Python3Spiders/WeiboSuperSpider#21]
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
I/O error : encoder error

就仅仅是在“输入cookie”那个地方塞了自己的微博cookie进去

**Comment by Mr-ZhouGH** [comment]
老哥，这个问题解决了吗

**Comment by EdelweissGriffin** [comment]
> 老哥，这个问题解决了吗

嗯，解决了

**Comment by Mr-ZhouGH** [comment]
> 
> 
> > 老哥，这个问题解决了吗
> 
> 嗯，解决了

老哥爬到数据了吗
