### ISSUE TITLE
时间段搜索失效

### ISSUE THREAD

**Issue by EdelweissGriffin** [Python3Spiders/WeiboSuperSpider#22]
我用WeiboTopicScrapy.py这个程序输入了关键词和时间段start_time='20190601', end_time='20190602'，但是返回的数据依旧是最新的当日数据

**Comment by EdelweissGriffin** [comment]
发现问题了，现在是可以直接到小时级，正确的时间段搜索方法是start_time='2019-06-01-0', end_time='2019-06-02-0'这种格式（年-月-日-时）

**Comment by inspurer** [comment]
试了下，貌似并不能支持小时级

**Comment by inspurer** [comment]
公众号【月小水长】文章更新了这个问题
