### ISSUE TITLE
请教评论爬取不全是什么原因？

### ISSUE THREAD

**Issue by jiangjocelyn** [Python3Spiders/WeiboSuperSpider#24]
无 GUI 功能独立版的WeiboCommentScrapy.py运行单个微博ID评论的时候50多个能爬30多个评论，导入CSV文件批量爬取的时候运行一半就会一直报错。菜鸡求教，谢谢！
 raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /comment/Ca3BigTRn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000000100828B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by inspurer** [comment]
应该是爬的太快了
