### ISSUE TITLE
WeiboTopicScrapy.py运行出错

### ISSUE THREAD

**Issue by htyhmn** [Python3Spiders/WeiboSuperSpider#26]
![image](https://user-images.githubusercontent.com/69563759/98062005-24664600-1e88-11eb-9516-f4df94099e2c.png)
问题出在哪里，运行平台是VScode，3.7版本，用的conda的环境

**Comment by inspurer** [comment]
cookie 复制错了，或者是你 anaconda安装的这个库编码不对
