### ISSUE TITLE
经常出现服务器走丢提示

### ISSUE THREAD

**Issue by barnett2010** [Python3Spiders/WeiboSuperSpider#3]
3万条的评论中，只能抓1200行代码

**Comment by barnett2010** [comment]
谢谢

在使用过程中有些问题。
抓话题，也是好多页一条都取不下来
第xxx 页...
第xxx页...

**Comment by barnett2010** [comment]
抓话题，取几年前的微博，会经常出现空跳页数，没取到内容
只好手动设置数字，每下载10天的，停下来改日期
可不可以改成，自动，10天自动改一次日期，重新下载
start time
endtime

**Comment by inspurer** [comment]
抓话题是因为有页数限制，每次搜索（指定话题和时间段）最多只能取到前 130 页左右；微博评论有时候可以获取到nw条，有时候只能nk。
