### ISSUE TITLE
话题爬虫获取不到数据

### ISSUE THREAD

**Issue by shizia** [Python3Spiders/WeiboSuperSpider#32]
你好！我在话题爬虫中遇到了问题，我使用的是无 GUI 版，在WeiboTopicScrapy.py中修改了keyword、starttime、endtime和cookie，检查过cookie复制无误。但是爬取到的微博数量为0，出现“自动结束，大概率是因为内容爬完了，也请留意是否是 cookie 失效等情况”的提示。想知道是否有解决方案呢？

**Comment by liyufei9611** [comment]
你的cookie不是https://weibo.cn/search/ 的
