### ISSUE TITLE
爬取中出现错误'latin-1' codec can't encode characters in position 0-6: ordinal not in range(256)

### ISSUE THREAD

**Issue by Kimchuls** [Python3Spiders/WeiboSuperSpider#34]
File "F:\anaconda_python3.7\anaconda_install\lib\http\client.py", line 1217, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-6: ordinal not in range(256)

**Comment by ATuxedo** [comment]
你这个问题大概是cookie没有设置好

**Comment by inspurer** [comment]
已更新新版本
