### ISSUE TITLE
topic spider

### ISSUE THREAD

**Issue by Mitty-ZH** [Python3Spiders/WeiboSuperSpider#35]
请问运行TopicScrapy出现 '自动结束，大概率是因为内容爬完了，也请留意是否是 cookie 失效等情况’ 是什么情况呢？相同的cookie在CommentScrapy中可以正常使用

**Comment by ATuxedo** [comment]
我也遇到了同样的问题

**Comment by inspurer** [comment]
可以转用最新版微博话题爬虫，首页 readme 有
