### ISSUE TITLE
用无gui下独立代码爬话题微博换了几个cookie都无结果，也不报错就是爬取数量为0

### ISSUE THREAD

**Issue by lalaxiaoer** [Python3Spiders/WeiboSuperSpider#36]

**Comment by inspurer** [comment]
可以用新版本的 https://mp.weixin.qq.com/s?__biz=MzUzMDE5MzQ3Ng==&mid=2247484943&idx=1&sn=b1c9520a388171932a9037dbd0ac5460&chksm=fa54cb24cd234232e62bec64881df16bcc1257b3e79628b57d562cd88ae9ffd91b883f15284d&scene=178&cur_album_id=1393531201285226497#rd
