### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by qehuang** [Python3Spiders/WeiboSuperSpider#39]
请问这是什么情况？谢谢。
ModuleNotFoundError: No module named 'NewSuperWeiboChildCommentsForMac'

**Comment by inspurer** [comment]
公众号里有说明，需要64位 Python3.6.6

**Comment by qehuang** [comment]
用的这个版本：
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

跑了test之后：
Traceback (most recent call last):
  File "/Users/elyse/Desktop/weibo/comment/test.py", line 1, in <module>
    from NewSuperWeiboChildCommentsForMac import main
ImportError: No module named NewSuperWeiboChildCommentsForMac

**Comment by qehuang** [comment]
用的这个版本：
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

跑了test之后：
Traceback (most recent call last):
File "./comment/test.py", line 1, in
from NewSuperWeiboChildCommentsForMac import main
ImportError: No module named NewSuperWeiboChildCommentsForMac

**Comment by inspurer** [comment]
看来是 Mac 的锅
