### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by OKISTD** [Python3Spiders/WeiboSuperSpider#4]
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
I/O error : encoder error
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
encoding error : input conversion failed due to input error, bytes 0xC3 0x87 0xC3 0x82
I/O error : encoder error

**Comment by inspurer** [comment]
cookie 错了，是 weibo.cn 的，不是 weibo.com

**Comment by OKISTD** [comment]
thank you！
