### ISSUE TITLE
评论爬取的两个问题

### ISSUE THREAD

**Issue by qehuang** [Python3Spiders/WeiboSuperSpider#41]
有两个问题请教，谢谢。
一是在json设置了limit为50，但是爬出来的远远不止，怎样才能控制数量呢？
二是有的微博显然有许多评论，可是一爬就出现data crawl finish或者system is busy，是什么情况？

**Comment by inspurer** [comment]
第一个问题：每翻 3 页才会判断一次是否超过 limit
第二个问题：判断微博的评论是否被控评（打开网页微博是否能看到），或者 cookie 需要登录登出，换个 ip
