### ISSUE TITLE
请问这个代码可以爬微博超话下 每条博文的图文吗 

### ISSUE THREAD

**Issue by HQ-LV** [Python3Spiders/WeiboSuperSpider#44]
您好 请问这个代码可以爬微博超话下 每条博文的图文吗 ？
谢谢

**Comment by inspurer** [comment]
可以的，看指南 docs，搜超话

**Comment by HQ-LV** [comment]
谢谢！我去找找看！





------------------ 原始邮件 ------------------
发件人: 月小水长 ***@***.***&gt;
发送时间: 2022年10月3日 17:39
收件人: Python3Spiders/WeiboSuperSpider ***@***.***&gt;
抄送: HQ-LV ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Python3Spiders/WeiboSuperSpider] 请问这个代码可以爬微博超话下 每条博文的图文吗  (Issue #44)





 
可以的，看指南 docs，搜超话
