### ISSUE TITLE
运行CommentedWeiboSpider.py，显示“SyntaxError: invalid non-printable character U+200B”错误

### ISSUE THREAD

**Issue by Tegfe** [Python3Spiders/WeiboSuperSpider#49]

**Comment by inspurer** [comment]
贴具体报错信息和截图

**Comment by Tegfe** [comment]
已经解决了，是因为段首的空格的问题，删除一个空格就能运行了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月29日 21:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Python3Spiders/WeiboSuperSpider] 运行CommentedWeiboSpider.py，显示“SyntaxError: invalid non-printable character U+200B”错误 (Issue #49) |

贴具体报错信息和截图

**Comment by inspurer** [comment]
ok，我也发现了
