### ISSUE TITLE
作者你好 我按照默认那个微博用户爬取的 出现了错误

### ISSUE THREAD

**Issue by puppyK** [Python3Spiders/WeiboSuperSpider#5]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "F:\python\anaconda\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:/微博数据/爬虫工具/WeiboSuperSpider-master/WeiboSuperSpider-master/无 GUI 功能独立版/WeiboCommentScrapy.py", line 161, in run
    self.write_to_csv(result,isHeader=False)
  File "E:/微博数据/爬虫工具/WeiboSuperSpider-master/WeiboSuperSpider-master/无 GUI 功能独立版/WeiboCommentScrapy.py", line 129, in write_to_csv
    with open('comment/' + self.wid + '.csv', 'a', encoding='utf-8-sig', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'comment/IaYZIu0Ko.csv'

是怎么回事呀

**Comment by inspurer** [comment]
这是因为你 excel 中打开了IaYZIu0Ko.csv

**Comment by puppyK** [comment]
感谢大佬  已经解决 正在爬取一个40万评论的微博 每天可能都有上万条新评论 可不可以设置按照日期每天爬取100条这样

**Comment by inspurer** [comment]
建议用 GUI 独立版中的微博评论爬虫，我爬了几 w 条评论

**Comment by puppyK** [comment]
我是用无gui独立版的微博评论爬虫 爬到50多页就无法抓取了 是不是被限制了

**Comment by inspurer** [comment]
可能是的

**Comment by puppyK** [comment]
额 那更改按日期爬取 比如每天爬取100条评论 3月1日100条 3月2日100条这样以此类推可以修改哪个地方呢

**Comment by puppyK** [comment]
您好 我试了几次都只能抓取50页 请问您在使用过程可以抓取更多评论吗  是不是微博评论目前只能抓去50页 还是我使用方法有问题

**Comment by inspurer** [comment]
用 WeiboSpuerCommentSrcapy.py 不是 WeiboCommentSrcapy.py

**Comment by puppyK** [comment]
感谢您 也看了您公众号上的一些详情 成功使用了 WeiboSpuerCommentSrcapy.py  不过有一个问题 程序评论爬取可否设定日期呢 比如有些评论几十万条 一天可能就有上万条 我想每日爬取500条这样

**Comment by inspurer** [comment]
暂时不能，抱歉

**Comment by puppyK** [comment]
程序好像有个bug 如果爬取比较少的评论 我试了一下 低于10条 就回一直重复爬取这10条

**Comment by passwordhk** [comment]
跳转的地方失败了  嗨呀
