### ISSUE TITLE
超话问题

### ISSUE THREAD

**Issue by skysunsun** [Python3Spiders/WeiboSuperSpider#52]
用话题爬取的超话数据不完全。话题用的是搜索，而超话有个独立的界面，请教大大，那超话爬取是不是跟评论爬取差不多？

**Comment by inspurer** [comment]
我一般用把关键词设置为 xx超话 来抓取超话内容的

**Comment by skysunsun** [comment]
这个确实可以，但是抓不完，我抓了个超话，10w的帖子，只抓到100条记录。哈哈哈哈&nbsp;


江天鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月30日(星期四) 下午3:20
收件人: "Python3Spiders/WeiboSuperSpider";
抄送: "Author";
主题: Re: [Python3Spiders/WeiboSuperSpider] 超话问题 (Issue #52)





 
我一般用把关键词设置为 xx超话 来抓取超话内容的
 
&mdash;

**Comment by inspurer** [comment]
试了下确实抓不全
